name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-generator:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Check out Git repository
        uses: actions/checkout@v3 
        with: 
          path: openapi-forge-typescript
       
      - name: Install Node.js dependencies
        run: |
          cd openapi-forge-typescript
          npm install

      - name: Check out the openapi-forge generator
        uses: actions/checkout@v3
        with: 
          repository: ScottLogic/openapi-forge
          path: openapi-forge

      - name: Install openapi-forge dependencies
        run: |
          cd openapi-forge
          npm install

      - name: Run the tests
        run: |
          cd openapi-forge-typescript
          npm test
